baseURL = "/"
languageCode = "en-us"
title = "Learning HUGO"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  author = "David Pine"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableAssetsBusting = false
  themeVariant = "red"

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github Repository"
identifier = "learn-hugo"
url = "https://github.com/IEvangelist/learn-hugo"
weight = 1

[[menu.shortcuts]]
name = "<i class='fab fa-twitter'></i> Follow @davidpine7"
identifier = "twitter"
url = "https://twitter.com/davidpine7"
weight = 2